// 414 CEDEARs parsed from BYMA PDF 16-Abr-2026
// Fuente: https://www.byma.com.ar/ (listado oficial 17-Abr-2026)
export interface Cedear {
  ticker: string
  name: string
  market: string
  ratio: string
}

export const CEDEARS: Cedear[] = [
  {"ticker":"AABA","name":"Altaba Inc.","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"AAL","name":"American Airlines Group Inc","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"AAP","name":"Advanced Auto Parts Inc","market":"NYSE","ratio":"14:1"},
  {"ticker":"AAPL","name":"Apple Inc.","market":"NASDAQ","ratio":"20:1"},
  {"ticker":"ABBV","name":"AbbVie Inc.","market":"NYSE","ratio":"10:1"},
  {"ticker":"ABEV","name":"Ambev S.A.","market":"NASDAQ","ratio":"1:3"},
  {"ticker":"ABEV3","name":"Ambev S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"ABNB","name":"Airbnb Inc","market":"NASDAQ GS","ratio":"15:1"},
  {"ticker":"ABT","name":"Abbott Labs","market":"NYSE","ratio":"4:1"},
  {"ticker":"ACN","name":"Accenture","market":"NYSE","ratio":"75:1"},
  {"ticker":"ACWI","name":"iShares MSCI ACWI ETF","market":"NASDAQ","ratio":"26:1"},
  {"ticker":"ADBE","name":"Adobe Systems Incorporated","market":"NASDAQ","ratio":"44:1"},
  {"ticker":"ADGO","name":"Adecoagro S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"ADI","name":"Analog Devices","market":"NASDAQ","ratio":"15:1"},
  {"ticker":"ADP","name":"Automatic Data Processing Inc.","market":"NASDAQ","ratio":"6:1"},
  {"ticker":"ADS","name":"Adidas AG","market":"XETRA","ratio":"22:1"},
  {"ticker":"AEG","name":"Aegon N.V.","market":"NYSE","ratio":"1:1"},
  {"ticker":"AEM","name":"Agnico Eagle Mines Limited","market":"NYSE","ratio":"6:1"},
  {"ticker":"AI","name":"C3.AI INC","market":"NYSE","ratio":"5:1"},
  {"ticker":"AIG","name":"American International Group (AIG)","market":"NYSE","ratio":"5:1"},
  {"ticker":"AKO.B","name":"Embotelladora Andina S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"ALAB","name":"Astera Labs Inc","market":"NASDAQ","ratio":"44:1"},
  {"ticker":"AMAT","name":"Applied Materials Inc.","market":"NASDAQ","ratio":"5:1"},
  {"ticker":"AMD","name":"Advanced Micro Devices, Inc.","market":"NASDAQ","ratio":"10:1"},
  {"ticker":"AMGN","name":"Amgen Inc.","market":"NASDAQ","ratio":"30:1"},
  {"ticker":"AMX","name":"America Movil","market":"NYSE","ratio":"1:1"},
  {"ticker":"AMZN","name":"Amazon.Com, Inc.","market":"NYSE","ratio":"144:1"},
  {"ticker":"ANF","name":"Abercrombie & Fitch Co","market":"NYSE","ratio":"1:1"},
  {"ticker":"AOCA","name":"Aluminum Corp Of China","market":"NYSE","ratio":"1:1"},
  {"ticker":"ARCO","name":"Arcos Dorados Holdings Inc.","market":"NYSE","ratio":"1:2"},
  {"ticker":"ARKK","name":"ARK INNOVATION","market":"NYSE Arca","ratio":"10:1"},
  {"ticker":"ARM","name":"ARM Holdings Plc","market":"NASDAQ","ratio":"27:1"},
  {"ticker":"ASML","name":"ASML HOLDING NV","market":"NASDAQ GS","ratio":"146:1"},
  {"ticker":"ASR","name":"Grupo Aeroportuario Del Sureste , S.A.B. de C.V.","market":"NYSE","ratio":"20:1"},
  {"ticker":"ASTS","name":"AST SpaceMobile Inc","market":"NASDAQ","ratio":"15:1"},
  {"ticker":"ATAD","name":"Pjsc Tatneft","market":"LONDON STOCK EXCHANGE","ratio":"4:1"},
  {"ticker":"AUY","name":"Yamana Gold Inc.","market":"NYSE","ratio":"1:1"},
  {"ticker":"AVGO","name":"Broadcom Inc.","market":"NASDAQ","ratio":"39:1"},
  {"ticker":"AVY","name":"Avery Dennison Corp.","market":"NYSE","ratio":"18:1"},
  {"ticker":"AXP","name":"American Express Co","market":"NYSE","ratio":"15:1"},
  {"ticker":"AZN","name":"Astrazeneca Plc","market":"NYSE","ratio":"4:1"},
  {"ticker":"B","name":"Barrick Gold Corp","market":"NYSE","ratio":"2:1"},
  {"ticker":"BA","name":"The Boeing Company","market":"NYSE","ratio":"24:1"},
  {"ticker":"BA.C","name":"Bank Of America Corporation","market":"NYSE","ratio":"4:1"},
  {"ticker":"BABA","name":"Alibaba Group Holding Limited","market":"NYSE","ratio":"9:1"},
  {"ticker":"BAK","name":"Braskem SA","market":"NYSE","ratio":"2:1"},
  {"ticker":"BAS","name":"Basf SE","market":"FRANKFURT","ratio":"2:1"},
  {"ticker":"BAYN","name":"Bayer AG","market":"FRANKFURT","ratio":"3:1"},
  {"ticker":"BB","name":"Blackberry Limited","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"BBAS3","name":"Banco do Brasil S.A.","market":"B3","ratio":"2:1"},
  {"ticker":"BBD","name":"Banco Bradesco S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"BBDC3","name":"Banco Bradesco S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"BBV","name":"Bilbao Vizcaya Argentaria S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"BCS","name":"Barclays Bank Plc","market":"NYSE","ratio":"1:1"},
  {"ticker":"BHP","name":"Bhp Group Ltd","market":"NYSE","ratio":"2:1"},
  {"ticker":"BIDU","name":"Baidu, Inc.","market":"NASDAQ","ratio":"11:1"},
  {"ticker":"BIIB","name":"Biogen Inc.","market":"NASDAQ","ratio":"13:1"},
  {"ticker":"BIOX","name":"Bioceres Crop Solutions Corp.","market":"NYSE American","ratio":"1:1"},
  {"ticker":"BK","name":"The Bank Of New York Mellon Corp.","market":"NYSE","ratio":"2:1"},
  {"ticker":"BKNG","name":"Booking","market":"NASDAQ","ratio":"700:1"},
  {"ticker":"BKR","name":"Baker Hughes Co","market":"NASDAQ","ratio":"7:1"},
  {"ticker":"BMNR","name":"Bitmine Inmersion Technologies, Inc.","market":"NYSE","ratio":"8:1"},
  {"ticker":"BMY","name":"Bristol-Myers Squibb Company","market":"NYSE","ratio":"3:1"},
  {"ticker":"BNG","name":"Bunge Limited","market":"NYSE","ratio":"5:1"},
  {"ticker":"BP","name":"BP PCL","market":"NYSE","ratio":"5:1"},
  {"ticker":"BPA11","name":"Banco BTG Pactual S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"BRFS","name":"BRF S.A.","market":"NYSE","ratio":"1:3"},
  {"ticker":"BRKB","name":"Berkshire Hathaway Inc.","market":"NYSE","ratio":"22:1"},
  {"ticker":"BSBR","name":"Banco Santander (Brasil) S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"BSN","name":"Danone","market":"FRANKFURT","ratio":"20:1"},
  {"ticker":"BX","name":"Blackstone Inc.","market":"NYSE","ratio":"30:1"},
  {"ticker":"C","name":"Citigroup Inc","market":"NYSE","ratio":"3:1"},
  {"ticker":"CAAP","name":"Corporación America Airports S.A.","market":"NYSE","ratio":"1:4"},
  {"ticker":"CAH","name":"Cardinal Health Inc","market":"NYSE","ratio":"3:1"},
  {"ticker":"CAJ","name":"Canon Inc","market":"NYSE","ratio":"2:1"},
  {"ticker":"CAR","name":"Avis Budget Group Inc.","market":"NASDAQ","ratio":"26:1"},
  {"ticker":"CAT","name":"Caterpillar Inc","market":"NYSE","ratio":"20:1"},
  {"ticker":"CBRD","name":"Companhia Brasileira De Dis NPV ADR","market":"NYSE","ratio":"1:1"},
  {"ticker":"CCL","name":"Carnival","market":"NYSE","ratio":"3:1"},
  {"ticker":"CDE","name":"Coeur Mining Inc.","market":"NYSE","ratio":"1:1"},
  {"ticker":"CEG","name":"CONSTELLATION ENERGY CORPORATION","market":"NASDAQ GS","ratio":"45:1"},
  {"ticker":"CIBR","name":"First Trust NASDAQ Cybersecurity","market":"NASDAQ GM","ratio":"10:1"},
  {"ticker":"CL","name":"Colgate Palmolive Co","market":"NYSE","ratio":"3:1"},
  {"ticker":"CLS","name":"CELESTICA INC","market":"NYSE","ratio":"20:1"},
  {"ticker":"COIN","name":"Coinbase Global Inc","market":"NASDAQ","ratio":"27:1"},
  {"ticker":"COPX","name":"Global X Copper Miners ETF","market":"NYSE","ratio":"14:1"},
  {"ticker":"COST","name":"Costco Wholesale Corp","market":"NASDAQ","ratio":"48:1"},
  {"ticker":"CRM","name":"Salesforce Inc.","market":"NYSE","ratio":"18:1"},
  {"ticker":"CRWV","name":"CoreWeave Inc","market":"NASDAQ","ratio":"27:1"},
  {"ticker":"CS","name":"Credit Suisse Group","market":"NYSE","ratio":"1:1"},
  {"ticker":"CSCO","name":"Cisco Systems Inc","market":"NASDAQ","ratio":"5:1"},
  {"ticker":"CSNA3","name":"Companhia Siderúrgica Nacional S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"CVS","name":"CVS Health","market":"NYSE","ratio":"15:1"},
  {"ticker":"CVX","name":"Chevron Corp.","market":"NYSE","ratio":"16:1"},
  {"ticker":"CX","name":"Cemex S.A.B. de CV","market":"NYSE","ratio":"1:1"},
  {"ticker":"DAL","name":"Delta Air Lines","market":"NYSE","ratio":"8:1"},
  {"ticker":"DD","name":"Dupont de Nemours Inc.","market":"NYSE","ratio":"5:1"},
  {"ticker":"DE","name":"Deere & Co.","market":"NYSE","ratio":"40:1"},
  {"ticker":"DECK","name":"DECKERS OUTDOOR CORPORATION","market":"NYSE","ratio":"25:1"},
  {"ticker":"DEO","name":"Diageo PLC","market":"NYSE","ratio":"6:1"},
  {"ticker":"DHR","name":"Danaher Corp","market":"NYSE","ratio":"54:1"},
  {"ticker":"DIA","name":"SPDR DOW JONES INDUSTRIAL","market":"NYSE Arca","ratio":"20:1"},
  {"ticker":"DISN","name":"The Walt Disney Co.","market":"NYSE","ratio":"12:1"},
  {"ticker":"DOCU","name":"DocuSign Inc.","market":"NASDAQ","ratio":"22:1"},
  {"ticker":"DOW","name":"DOW Inc","market":"NYSE","ratio":"6:1"},
  {"ticker":"DTEA","name":"Deutsche Telekom Ag","market":"OTC US","ratio":"3:1"},
  {"ticker":"E","name":"Eni Spa","market":"NYSE","ratio":"4:1"},
  {"ticker":"EA","name":"Electronic Arts Inc","market":"NASDAQ","ratio":"14:1"},
  {"ticker":"EBAY","name":"Ebay Inc.","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"EBR","name":"Centrais Eléctricas Brasileiras S.A. - Eletrobras","market":"NYSE","ratio":"1:4"},
  {"ticker":"ECL","name":"Ecolab Inc","market":"NYSE","ratio":"56:1"},
  {"ticker":"EEM","name":"ISHARES MSCI EMERGING MARKET","market":"NYSE Arca","ratio":"5:1"},
  {"ticker":"EFA","name":"iShares MSCI EAFE ETF","market":"NYSE","ratio":"18:1"},
  {"ticker":"EFX","name":"Equifax Inc.","market":"NYSE","ratio":"16:1"},
  {"ticker":"ELP","name":"Companhia Paranaense de Energía - COPEL","market":"NYSE","ratio":"1:3"},
  {"ticker":"EOAN","name":"E.On Se","market":"FRANKFURT","ratio":"6:1"},
  {"ticker":"EQNR","name":"Equinor Asa","market":"NYSE","ratio":"6:1"},
  {"ticker":"ERIC","name":"Lm Ericsson Telephone Co.","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"ERJ","name":"Embraer-Empresa Brasileira de Aeronáutica S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"ESGU","name":"IShares ESG Aware MSCI USA ETF","market":"NASDAQ","ratio":"30:1"},
  {"ticker":"ETHA","name":"ISHARES ETHEREUM TR ETF","market":"NASDAQ","ratio":"5:1"},
  {"ticker":"ETSY","name":"Etsy Inc.","market":"NASDAQ","ratio":"16:1"},
  {"ticker":"EWJ","name":"iShares MSCI JAPAN ETF","market":"NYSE Arca","ratio":"14:1"},
  {"ticker":"EWY","name":"iShares MSCI South Korea ETF","market":"NYSE ARCA","ratio":"50:1"},
  {"ticker":"EWZ","name":"ISHARES MSCI BRAZIL CAP","market":"NYSE Arca","ratio":"2:1"},
  {"ticker":"F","name":"Ford Motor Company","market":"NYSE","ratio":"1:1"},
  {"ticker":"FCX","name":"Freeport Mcmoran Copper & Gold Inc.","market":"NYSE","ratio":"3:1"},
  {"ticker":"FDX","name":"Fedex Corp","market":"NYSE","ratio":"10:1"},
  {"ticker":"FMCC","name":"Freddie Mac (Federal Home Loan)","market":"OTC","ratio":"1:1"},
  {"ticker":"FMX","name":"Fomento Economico Mexicano - Femsa","market":"NYSE","ratio":"6:1"},
  {"ticker":"FNMA","name":"Fed. Natl, Mortgage - Fannie Mae","market":"OTC","ratio":"1:1"},
  {"ticker":"FSLR","name":"First Solar Inc.","market":"NASDAQ","ratio":"18:1"},
  {"ticker":"FXI","name":"ISHARES CHINA LARGE-CAP ETF","market":"NYSE","ratio":"5:1"},
  {"ticker":"GDX","name":"Van Eck Gold Miners ETF/USA","market":"NYSE","ratio":"10:1"},
  {"ticker":"GE","name":"General Electric Co.","market":"NYSE","ratio":"8:1"},
  {"ticker":"GFI","name":"Gold Fields Ltd.","market":"NYSE","ratio":"1:1"},
  {"ticker":"GGB","name":"Gerdau S.A.","market":"NYSE","ratio":"1:4"},
  {"ticker":"GILD","name":"Gilead Sciences, Inc.","market":"NASDAQ","ratio":"4:1"},
  {"ticker":"GLD","name":"ETF SPDR GOLD TRUST","market":"NYSE","ratio":"50:1"},
  {"ticker":"GLOB","name":"Globant S.A.","market":"NYSE","ratio":"18:1"},
  {"ticker":"GLW","name":"Corning Inc.","market":"NYSE","ratio":"4:1"},
  {"ticker":"GM","name":"General Motors Co","market":"NYSE","ratio":"6:1"},
  {"ticker":"GOOGL","name":"Alphabet Inc.","market":"NASDAQ","ratio":"58:1"},
  {"ticker":"GPRK","name":"Geopark Ltd.","market":"NYSE","ratio":"1:1"},
  {"ticker":"GRMN","name":"Garmin Ltd.","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"GS","name":"The Goldman Sachs Group, Inc","market":"NYSE","ratio":"13:1"},
  {"ticker":"GSK","name":"GSK Plc.","market":"NYSE","ratio":"4:1"},
  {"ticker":"GT","name":"Goodyear Tire & Rubber co./the","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"HAL","name":"Halliburton Co.","market":"NYSE","ratio":"2:1"},
  {"ticker":"HAPV3","name":"Hapvida Participacoes E Investimentos S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"HD","name":"The Home Depot Inc.","market":"NYSE","ratio":"32:1"},
  {"ticker":"HDB","name":"Hdfc Bank Limited.","market":"NYSE","ratio":"2:1"},
  {"ticker":"HHPD","name":"Hon Hai Precision Industry Co. Ltd.","market":"LONDON STOCK EXCHANGE","ratio":"2:1"},
  {"ticker":"HL","name":"Hecla Mining Co .","market":"NYSE","ratio":"1:1"},
  {"ticker":"HMC","name":"Honda Motor Co. Ltd","market":"NYSE","ratio":"1:1"},
  {"ticker":"HMY","name":"Harmony Gold Mining Company Ltd.","market":"NYSE","ratio":"1:1"},
  {"ticker":"HNPIY","name":"Huaneng Power Intl","market":"NYSE","ratio":"1:1"},
  {"ticker":"HOG","name":"Harley-Davidson Inc.","market":"NYSE","ratio":"3:1"},
  {"ticker":"HON","name":"Honeywell International Inc.","market":"NYSE","ratio":"8:1"},
  {"ticker":"HOOD","name":"Robinhood Markets Inc","market":"NASDAQ","ratio":"29:1"},
  {"ticker":"HPQ","name":"Hp Inc","market":"NYSE","ratio":"1:1"},
  {"ticker":"HSBC","name":"Hsbc Holdings Plc","market":"NYSE","ratio":"2:1"},
  {"ticker":"HSY","name":"The Hershey Company","market":"NYSE","ratio":"21:1"},
  {"ticker":"HUT","name":"Hut 8 Mining Corp.","market":"NASDAQ GS","ratio":"1:5"},
  {"ticker":"HWM","name":"Howmet Aerospace Inc.","market":"NYSE","ratio":"1:1"},
  {"ticker":"IBB","name":"iShares Nasdaq Biotechnology ETF","market":"NASDAQ","ratio":"27:1"},
  {"ticker":"IBIT","name":"ISHARES BITCOIN TRUST","market":"NASDAQ","ratio":"10:1"},
  {"ticker":"IBM","name":"International Business Machines","market":"NYSE","ratio":"15:1"},
  {"ticker":"IBN","name":"Icici Bank Ltd.","market":"NYSE","ratio":"1:1"},
  {"ticker":"ICLN","name":"iShares Global Clean Energy ETF","market":"NASDAQ GM","ratio":"5:1"},
  {"ticker":"IEMG","name":"iShares Core MSCI Emerging Markets ETF","market":"NYSE","ratio":"12:1"},
  {"ticker":"IEUR","name":"iShares Core MSCI Europe ETF","market":"NYSE Arca","ratio":"11:1"},
  {"ticker":"IFF","name":"International Flavors & Fragrances Inc.","market":"NYSE","ratio":"12:1"},
  {"ticker":"IJH","name":"iShares CORE S&P MID-CAP ETF","market":"NYSE Arca","ratio":"12:1"},
  {"ticker":"ILF","name":"IShares Latin America 40 ETF","market":"NYSE","ratio":"6:1"},
  {"ticker":"INFY","name":"Infosys Limited","market":"NASDAQ","ratio":"1:1"},
  {"ticker":"ING","name":"Ing Groep Nv","market":"NYSE","ratio":"3:1"},
  {"ticker":"INTC","name":"Intel Corporation","market":"NASDAQ","ratio":"5:1"},
  {"ticker":"IP","name":"International Paper Co.","market":"NYSE","ratio":"4:1"},
  {"ticker":"IREN","name":"Iren Ltd","market":"NASDAQ","ratio":"12:1"},
  {"ticker":"ISRG","name":"Intuitive Surgical inc","market":"NASDAQ","ratio":"90:1"},
  {"ticker":"ITA","name":"iShares U.S. Aerospace & Defense","market":"CBOE","ratio":"50:1"},
  {"ticker":"ITUB","name":"Itaú Unibanco Holding S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"ITUB3","name":"Banco Itaú Unibanco S.A","market":"B3","ratio":"1:1"},
  {"ticker":"IVE","name":"iShares S&P 500 Value ETF","market":"NYSE Arca","ratio":"40:1"},
  {"ticker":"IVV","name":"IShares Core S&P 500 ETF","market":"NYSE","ratio":"692:1"},
  {"ticker":"IVW","name":"iShares S&P 500 Growth ETF","market":"NYSE Arca","ratio":"20:1"},
  {"ticker":"IWM","name":"ISHARES TRUST RUSSELL 2000","market":"NYSE Arca","ratio":"10:1"},
  {"ticker":"JCI","name":"Johnson Controls International","market":"NYSE","ratio":"2:1"},
  {"ticker":"JD","name":"Jd.Com, Inc.","market":"NASDAQ","ratio":"4:1"},
  {"ticker":"JMIA","name":"Adr Jumia Technologies Ag","market":"NYSE","ratio":"1:1"},
  {"ticker":"JNJ","name":"Johnson & Johnson","market":"NYSE","ratio":"15:1"},
  {"ticker":"JOYY","name":"JOYY Inc.","market":"NASDAQ","ratio":"5:1"},
  {"ticker":"JPM","name":"J.P. Morgan & Chase Co.","market":"NYSE","ratio":"15:1"},
  {"ticker":"KB","name":"Kb Financial Group Inc.","market":"NYSE","ratio":"2:1"},
  {"ticker":"KEEL","name":"Bitfarms Ltd.","market":"NASDAQ GM","ratio":"1:5"},
  {"ticker":"KEP","name":"Korea Electric Power Corp.","market":"NYSE","ratio":"1:1"},
  {"ticker":"KGC","name":"Kinross Gold Corp","market":"NYSE","ratio":"1:1"},
  {"ticker":"KMB","name":"Kimberly-Clark Corp.","market":"NYSE","ratio":"6:1"},
  {"ticker":"KO","name":"The Coca Cola Company","market":"NYSE","ratio":"5:1"},
  {"ticker":"KOFM","name":"Coca-Cola Femsa, S.A.B. De C.V.","market":"NYSE","ratio":"2:1"},
  {"ticker":"LAC","name":"Lithium Americas Corp","market":"NYSE","ratio":"1:1"},
  {"ticker":"LAR","name":"Lithium Americas (Argentina) Corp","market":"NYSE","ratio":"1:1"},
  {"ticker":"LFC","name":"China Life Insurance","market":"NYSE","ratio":"2:1"},
  {"ticker":"LKOD","name":"Pjsc Lukoil","market":"LONDON STOCK EXCHANGE","ratio":"4:1"},
  {"ticker":"LLY","name":"Eli Lilly and Company","market":"NYSE","ratio":"56:1"},
  {"ticker":"LMT","name":"Lockheed Martin Corporation","market":"NYSE","ratio":"20:1"},
  {"ticker":"LND","name":"Brasilagro - Co Brasileira de Propriedades Agrícolas","market":"NYSE","ratio":"1:1"},
  {"ticker":"LRCX","name":"Lam Research Corp","market":"NASDAQ","ratio":"56:1"},
  {"ticker":"LREN3","name":"Lojas Renner S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"LVS","name":"Las Vegas Sands Corp","market":"NYSE","ratio":"2:1"},
  {"ticker":"LYG","name":"Lloyds Banking Group Plc","market":"NYSE","ratio":"2:1"},
  {"ticker":"MA","name":"Mastercard Inc.","market":"NYSE","ratio":"33:1"},
  {"ticker":"MBG","name":"Mercedes-Benz Group AG","market":"FRANKFURT","ratio":"4:1"},
  {"ticker":"MBT","name":"Mobile Telesystems","market":"NYSE","ratio":"2:1"},
  {"ticker":"MCD","name":"Mcdonald'S Corp.","market":"NYSE","ratio":"24:1"},
  {"ticker":"MDLZ","name":"Mondelez","market":"NASDAQ","ratio":"15:1"},
  {"ticker":"MDT","name":"Medtronic Public Limited Company","market":"NYSE","ratio":"4:1"},
  {"ticker":"MELI","name":"Mercadolibre Inc.","market":"NASDAQ","ratio":"120:1"},
  {"ticker":"META","name":"Meta Platforms Inc","market":"NASDAQ","ratio":"24:1"},
  {"ticker":"MFG","name":"Mizuho Financial Group","market":"NYSE","ratio":"1:1"},
  {"ticker":"MGLU3","name":"Magazine Luiza S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"MMC","name":"Marsh & Mclennan Companies Inc.","market":"NYSE","ratio":"16:1"},
  {"ticker":"MMM","name":"3M Company","market":"NYSE","ratio":"10:1"},
  {"ticker":"MO","name":"Altria Group Inc.","market":"NYSE","ratio":"4:1"},
  {"ticker":"MOS","name":"The Mosaic Co","market":"NYSE","ratio":"5:1"},
  {"ticker":"MRK","name":"Merck & Co. Inc.","market":"NYSE","ratio":"5:1"},
  {"ticker":"MRNA","name":"Moderna Inc","market":"NASDAQ","ratio":"19:1"},
  {"ticker":"MRVL","name":"Marvell Technology Inc","market":"NASDAQ","ratio":"14:1"},
  {"ticker":"MSFT","name":"Microsoft Corp.","market":"NASDAQ","ratio":"30:1"},
  {"ticker":"MSI","name":"Motorola Solutions, Inc.","market":"NYSE","ratio":"20:1"},
  {"ticker":"MSTR","name":"Microstrategy Inc Cl A New","market":"NASDAQ GS","ratio":"20:1"},
  {"ticker":"MU","name":"Micron Technology Inc","market":"NASDAQ GS","ratio":"5:1"},
  {"ticker":"MUFG","name":"Mitsubishi Ufj Financial Group","market":"NYSE","ratio":"1:1"},
  {"ticker":"MUX","name":"McEwen Mining Inc","market":"NYSE","ratio":"2:1"},
  {"ticker":"NATU3","name":"NATURA COSMETICOS SA","market":"B3","ratio":"1:1"},
  {"ticker":"NEC1","name":"Nec Corporation","market":"FRANKFURT","ratio":"1:3"},
  {"ticker":"NEM","name":"Newmont Corporation","market":"NYSE","ratio":"3:1"},
  {"ticker":"NFLX","name":"Netflix, Inc.","market":"NASDAQ","ratio":"48:1"},
  {"ticker":"NG","name":"Novagold Resources INC.","market":"NYSE","ratio":"1:4"},
  {"ticker":"NGG","name":"National Grid Plc","market":"NYSE","ratio":"2:1"},
  {"ticker":"NIO","name":"NIO Inc.","market":"NYSE","ratio":"4:1"},
  {"ticker":"NKE","name":"Nike Inc.","market":"NYSE","ratio":"12:1"},
  {"ticker":"NLM","name":"Novolipetsk Steel PJSC","market":"LONDON STOCK EXCHANGE","ratio":"2:1"},
  {"ticker":"NMR","name":"Nomura Holdings, Inc","market":"NYSE","ratio":"1:1"},
  {"ticker":"NOKA","name":"Nokia Corporation","market":"NYSE","ratio":"1:1"},
  {"ticker":"NOW","name":"SERVICENOW INC","market":"NYSE","ratio":"172:1"},
  {"ticker":"NSAN","name":"Nissan Motor Co., Ltd","market":"OTC US","ratio":"1:1"},
  {"ticker":"NTES","name":"Netease, Inc","market":"NASDAQ","ratio":"14:1"},
  {"ticker":"NUE","name":"Nucor Corp","market":"NYSE","ratio":"16:1"},
  {"ticker":"NVDA","name":"Nvidia Corporation","market":"NASDAQ","ratio":"24:1"},
  {"ticker":"NVS","name":"Novartis Ag","market":"NYSE","ratio":"4:1"},
  {"ticker":"NXE","name":"Nexgen Energy LTD","market":"NYSE","ratio":"1:1"},
  {"ticker":"OGZD","name":"Pjsc Gazprom","market":"LONDON STOCK EXCHANGE","ratio":"2:1"},
  {"ticker":"OKLO","name":"Oklo Inc","market":"NYSE","ratio":"28:1"},
  {"ticker":"ORAN","name":"Orange S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"ORCL","name":"Oracle Corporation","market":"NYSE","ratio":"3:1"},
  {"ticker":"ORLY","name":"O'reilly Automotive Inc","market":"NASDAQ","ratio":"222:1"},
  {"ticker":"OXY","name":"Occidental Petroleum Corp.","market":"NYSE","ratio":"5:1"},
  {"ticker":"PAAS","name":"Pan American Silver Corp.","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"PAC","name":"Grupo Aeroportuario del Pacifico, S.A.B. de C.V.","market":"NYSE","ratio":"16:1"},
  {"ticker":"PAGS","name":"Pagseguro Digital Ltd","market":"NYSE","ratio":"3:1"},
  {"ticker":"PANW","name":"Palo Alto Networks Inc","market":"NASDAQ GS","ratio":"50:1"},
  {"ticker":"PATH","name":"UIPATH INC","market":"NYSE","ratio":"2:1"},
  {"ticker":"PBI","name":"Pitney Bowes Inc","market":"NYSE","ratio":"1:1"},
  {"ticker":"PBR","name":"Petrobras (ADR)","market":"NYSE","ratio":"1:1"},
  {"ticker":"PCAR","name":"Paccar Inc.","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"PCRF","name":"Panasonic Corporation","market":"OTC US","ratio":"2:1"},
  {"ticker":"PDD","name":"PDD HOLDINGS INC","market":"NASDAQ GS","ratio":"25:1"},
  {"ticker":"PEP","name":"Pepsico Inc","market":"NASDAQ","ratio":"18:1"},
  {"ticker":"PETR3","name":"Petrobras - Petróleo Brasileiro S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"PFE","name":"Pfizer Inc.","market":"NYSE","ratio":"4:1"},
  {"ticker":"PG","name":"Procter & Gamble","market":"NYSE","ratio":"15:1"},
  {"ticker":"PHG","name":"Koninklijke Philips N.V.","market":"NYSE","ratio":"5:1"},
  {"ticker":"PINS","name":"Pinterest","market":"NYSE","ratio":"7:1"},
  {"ticker":"PKS","name":"Posco Holdings Inc.","market":"NYSE","ratio":"3:1"},
  {"ticker":"PLTR","name":"Palantir Technologies Inc","market":"NYSE","ratio":"3:1"},
  {"ticker":"PM","name":"Philip Morris International","market":"NYSE","ratio":"18:1"},
  {"ticker":"PRIO3","name":"Petro Rio S.A.","market":"B3","ratio":"2:1"},
  {"ticker":"PSO","name":"Pearson Plc","market":"NYSE","ratio":"1:1"},
  {"ticker":"PSQ","name":"PROSHARES SHORT QQQ","market":"NYSE Arca","ratio":"8:1"},
  {"ticker":"PSX","name":"Phillips 66","market":"NYSE","ratio":"6:1"},
  {"ticker":"PTR","name":"Petrochina Co Ltd","market":"NYSE","ratio":"4:1"},
  {"ticker":"PYPL","name":"Paypal Holdings, Inc.","market":"NASDAQ","ratio":"8:1"},
  {"ticker":"QCOM","name":"Qualcomm Inc.","market":"NASDAQ","ratio":"11:1"},
  {"ticker":"QQQ","name":"INVESCO QQQ TRUST","market":"NASDAQ","ratio":"20:1"},
  {"ticker":"RACE","name":"Ferrari","market":"NYSE","ratio":"83:1"},
  {"ticker":"RBLX","name":"Roblox Corp.","market":"NYSE","ratio":"2:1"},
  {"ticker":"RCTB4","name":"Telebras PN","market":"BOVESPA","ratio":"1:1000"},
  {"ticker":"RENT3","name":"Localiza Rent A Car S.A.","market":"B3","ratio":"2:1"},
  {"ticker":"RGTI","name":"RIGETTI COMPUTING INC","market":"NASDAQ CM","ratio":"2:1"},
  {"ticker":"RIO","name":"Rio Tinto Plc","market":"NYSE","ratio":"8:1"},
  {"ticker":"RIOT","name":"Riot Platforms","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"RKLB","name":"Rocket Lab Corp","market":"NASDAQ","ratio":"12:1"},
  {"ticker":"ROKU","name":"Roku","market":"NASDAQ","ratio":"13:1"},
  {"ticker":"ROST","name":"Ross Stores, Inc.","market":"NASDAQ","ratio":"4:1"},
  {"ticker":"RSP","name":"Invesco S&P 500 eql wght ETF","market":"NYSE ARCA","ratio":"30:1"},
  {"ticker":"RTX","name":"Raytheon Technologies Corp","market":"NYSE","ratio":"5:1"},
  {"ticker":"SAN","name":"Banco Santander S.A","market":"NYSE","ratio":"1:4"},
  {"ticker":"SAP","name":"Sap Se","market":"NYSE","ratio":"6:1"},
  {"ticker":"SATL","name":"Satellogic Inc.","market":"NASDAQ GS","ratio":"1:1"},
  {"ticker":"SBS","name":"Companhia de Saneamento Básico do Estado de São Paulo–Sabesp","market":"NYSE","ratio":"1:2"},
  {"ticker":"SBSP3","name":"Cia Saneamento Básico de SP","market":"B3","ratio":"1:1"},
  {"ticker":"SBUX","name":"Starbucks Corporation","market":"NASDAQ","ratio":"12:1"},
  {"ticker":"SCCO","name":"Southern Copper Corp","market":"NYSE","ratio":"2:1"},
  {"ticker":"SCHW","name":"Charles Schwab","market":"NYSE","ratio":"13:1"},
  {"ticker":"SDA","name":"SunCar Technology Group Inc","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"SE","name":"Sea Ltd.","market":"NYSE","ratio":"32:1"},
  {"ticker":"SH","name":"PROSHARES SHORT S&P500","market":"NYSE","ratio":"8:1"},
  {"ticker":"SHEL","name":"Royal Dutch Shell Plc","market":"NYSE","ratio":"2:1"},
  {"ticker":"SHOP","name":"Shopify Inc.","market":"NYSE","ratio":"107:1"},
  {"ticker":"SHPW","name":"Shapeways Holdings Inc","market":"NYSE","ratio":"1:2"},
  {"ticker":"SI","name":"Silvergate Bancorp","market":"NYSE","ratio":"10:1"},
  {"ticker":"SID","name":"Companhia Siderúrgica Nacional","market":"NYSE","ratio":"1:8"},
  {"ticker":"SIEGY","name":"Siemens Ag Adr","market":"OTC","ratio":"3:1"},
  {"ticker":"SLB","name":"Schlumberger Ltd","market":"NYSE","ratio":"3:1"},
  {"ticker":"SLV","name":"iShares SILVER TRUST","market":"NYSE Arca","ratio":"6:1"},
  {"ticker":"SMH","name":"VAN ECK SEMICONDUCTOR ETF","market":"NASDAQ","ratio":"50:1"},
  {"ticker":"SMSN","name":"Samsung Electronics Co. Ltd.","market":"LONDON STOCK EXCHANGE","ratio":"14:1"},
  {"ticker":"SNA","name":"Snap-On Inc","market":"NYSE","ratio":"6:1"},
  {"ticker":"SNAP","name":"Snap Inc.","market":"NYSE","ratio":"1:1"},
  {"ticker":"SNOW","name":"Snowflake Inc.","market":"NYSE","ratio":"30:1"},
  {"ticker":"SNP","name":"China Petroleum & Chem","market":"NYSE","ratio":"3:1"},
  {"ticker":"SONY","name":"Sony Group Corporation","market":"NYSE","ratio":"8:1"},
  {"ticker":"SPCE","name":"Virgin Galactic","market":"NYSE","ratio":"1:2"},
  {"ticker":"SPGI","name":"S&P Global Inc","market":"NYSE","ratio":"45:1"},
  {"ticker":"SPHQ","name":"Invesco S&P 500 quality ETF","market":"NYSE ARCA","ratio":"14:1"},
  {"ticker":"SPOT","name":"Spotify Technology S.A.","market":"NYSE","ratio":"28:1"},
  {"ticker":"SPXL","name":"DIREXION DAILY S&P 500 BULL 3X","market":"NYSE Arca","ratio":"25:1"},
  {"ticker":"SPY","name":"SPDR S&P 500","market":"NYSE Arca","ratio":"20:1"},
  {"ticker":"STLA","name":"Stellantis","market":"NYSE","ratio":"5:1"},
  {"ticker":"STNE","name":"StoneCo Ltd","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"SUZ","name":"Suzano Papel E Celulose S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"SUZB3","name":"Suzano S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"SWKS","name":"Skyworks Solutions","market":"NASDAQ","ratio":"21:1"},
  {"ticker":"SYY","name":"Sysco Corp.","market":"NYSE","ratio":"8:1"},
  {"ticker":"T","name":"At &T Inc.","market":"NYSE","ratio":"3:1"},
  {"ticker":"TCOM","name":"TRIP.COM Group Ltd.","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"TEAM","name":"ATLASSIAN CORPORATION","market":"NASDAQ GS","ratio":"47:1"},
  {"ticker":"TEFO","name":"Telefonica S.A.","market":"NYSE","ratio":"8:1"},
  {"ticker":"TEM","name":"TEMPUS AI INC","market":"NASDAQ GS","ratio":"12:1"},
  {"ticker":"TEN","name":"Tenaris","market":"NYSE","ratio":"1:1"},
  {"ticker":"TGT","name":"Target Corporation","market":"NYSE","ratio":"24:1"},
  {"ticker":"TIIAY","name":"Telecom Italia S.P.A. Ordinary Shares","market":"NYSE","ratio":"1:1"},
  {"ticker":"TIMB","name":"Tim Participações S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"TIMS3","name":"TIM S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"TJX","name":"TJX Companies Inc/The","market":"NYSE","ratio":"22:1"},
  {"ticker":"TM","name":"Toyota Motor Corporation","market":"NYSE","ratio":"15:1"},
  {"ticker":"TMO","name":"Thermo Fisher Scientific Inc.","market":"NYSE","ratio":"22:1"},
  {"ticker":"TMUS","name":"T-mobile","market":"NASDAQ","ratio":"33:1"},
  {"ticker":"TQQQ","name":"ProShares UltraPro QQQ","market":"NASDAQ","ratio":"25:1"},
  {"ticker":"TRIP","name":"Tripadvisor, Inc.","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"TRVV","name":"The Travelers Cos. Inc.","market":"NYSE","ratio":"6:1"},
  {"ticker":"TSLA","name":"Tesla, Inc.","market":"NASDAQ","ratio":"15:1"},
  {"ticker":"TSM","name":"Taiwan Semiconductor Manufacturing","market":"NYSE","ratio":"9:1"},
  {"ticker":"TTE","name":"TotalEnergies SE","market":"NYSE","ratio":"3:1"},
  {"ticker":"TTM","name":"Tata Motors Ltd","market":"NYSE","ratio":"1:1"},
  {"ticker":"TV","name":"Grupo Televisa S.A.","market":"NYSE","ratio":"3:1"},
  {"ticker":"TWLO","name":"Twilio Inc","market":"NYSE","ratio":"36:1"},
  {"ticker":"TWTR","name":"Twitter, Inc.","market":"NYSE","ratio":"2:1"},
  {"ticker":"TXN","name":"Texas Instruments Inc","market":"NASDAQ","ratio":"5:1"},
  {"ticker":"TXR","name":"Ternium S.A.","market":"NYSE","ratio":"4:1"},
  {"ticker":"UAL","name":"United Airlines Holdings Inc.","market":"NASDAQ GS","ratio":"5:1"},
  {"ticker":"UBER","name":"Uber Technologies Inc.","market":"NYSE","ratio":"2:1"},
  {"ticker":"UGP","name":"Ultrapar Participações S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"UL","name":"Unilever PLC - Sponsored","market":"NYSE","ratio":"3:1"},
  {"ticker":"UN","name":"NU Holdings Ltd/Cayman Islands","market":"NYSE","ratio":"2:1"},
  {"ticker":"UNH","name":"UnitedHealth Group Inc.","market":"NYSE","ratio":"33:1"},
  {"ticker":"UNP","name":"Union Pacific Corp.","market":"NYSE","ratio":"20:1"},
  {"ticker":"UPST","name":"Upstart Hldgs Inc","market":"NASDAQ GS","ratio":"5:1"},
  {"ticker":"URA","name":"Global X Uranium ETF","market":"NYSE Arca","ratio":"5:1"},
  {"ticker":"URBN","name":"Urban Outfitters INC.","market":"NASDAQ","ratio":"2:1"},
  {"ticker":"USB","name":"U.S. Bancorp","market":"NYSE","ratio":"5:1"},
  {"ticker":"USO","name":"United States Oil Fund","market":"NYSE","ratio":"15:1"},
  {"ticker":"V","name":"Visa Inc","market":"NYSE","ratio":"18:1"},
  {"ticker":"VALE","name":"Vale S.A.","market":"NYSE","ratio":"2:1"},
  {"ticker":"VALE3","name":"Vale S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"VEA","name":"Vanguard FTSE Developed Markets ETF","market":"NYSE Arca","ratio":"10:1"},
  {"ticker":"VIG","name":"VANGUARD DIVIDEND APPRECIATION","market":"NYSE Arca","ratio":"39:1"},
  {"ticker":"VIST","name":"Vista Energy S.A.B. de C.V.","market":"NYSE","ratio":"3:1"},
  {"ticker":"VIV","name":"Telefônica Brasil S.A.","market":"NYSE","ratio":"1:1"},
  {"ticker":"VIVT3","name":"Telefônica Brasil S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"VOD","name":"Vodafone Group Plc","market":"NASDAQ","ratio":"1:1"},
  {"ticker":"VRSN","name":"Verisign, Inc.","market":"-","ratio":"6:1"},
  {"ticker":"VRTX","name":"VERTEX PHARMACEUTICALS INC","market":"NYSE","ratio":"101:1"},
  {"ticker":"VST","name":"VISTRA CORPORATION","market":"NYSE","ratio":"26:1"},
  {"ticker":"VXX","name":"iPath Series B S&P 500 VIX","market":"CBOE","ratio":"5:1"},
  {"ticker":"VZ","name":"Verizon Communications Inc.","market":"NYSE","ratio":"4:1"},
  {"ticker":"WBA","name":"Walgreens Boots Alliance Inc.","market":"NASDAQ","ratio":"3:1"},
  {"ticker":"WBO","name":"Weibo Corporation","market":"NASDAQ","ratio":"6:1"},
  {"ticker":"WEGE3","name":"Weg S.A.","market":"B3","ratio":"1:1"},
  {"ticker":"WFC","name":"Wells Fargo & Co.","market":"NYSE","ratio":"5:1"},
  {"ticker":"WMT","name":"Walmart Inc.","market":"NYSE","ratio":"18:1"},
  {"ticker":"XLB","name":"The Materials Select Sector SPDR Fund","market":"NYSE Arca","ratio":"18:1"},
  {"ticker":"XLC","name":"The Communication Services Select Sector SPDR Fund","market":"NYSE Arca","ratio":"19:1"},
  {"ticker":"XLE","name":"ENERGY SELECT SECTOR SPDR FUND","market":"NYSE Arca","ratio":"2:1"},
  {"ticker":"XLF","name":"FINANCIAL SELECT SECTOR SPDR FUND","market":"NYSE Arca","ratio":"2:1"},
  {"ticker":"XLI","name":"The Industrial Select Sector SPDR Fund","market":"NYSE Arca","ratio":"28:1"},
  {"ticker":"XLK","name":"The Technology Select Sector SPDR Fund","market":"NYSE Arca","ratio":"46:1"},
  {"ticker":"XLP","name":"The Consumer Staples Select Sector SPDR Fund","market":"NYSE Arca","ratio":"16:1"},
  {"ticker":"XLRE","name":"The Real Estate Select Sector SPDR Fund","market":"NYSE Arca","ratio":"9:1"},
  {"ticker":"XLU","name":"First Trust NASDAQ Cybersecurity","market":"NASDAQ","ratio":"10:1"},
  {"ticker":"XLU","name":"Utilities Select Sector SPDR Fund","market":"NYSE Arca","ratio":"15:1"},
  {"ticker":"XLV","name":"The Health Care Select Sector SPDR Fund","market":"NYSE Arca","ratio":"29:1"},
  {"ticker":"XLY","name":"The Consumer Discretionary Select Sector SPDR Fund","market":"NYSE Arca","ratio":"43:1"},
  {"ticker":"XME","name":"State Street SPDR S&P Metals & Mining ETF","market":"NYSE ARCA","ratio":"30:1"},
  {"ticker":"XOM","name":"Exxon Mobil Corporation","market":"NYSE","ratio":"10:1"},
  {"ticker":"XP","name":"XP Inc","market":"NASDAQ","ratio":"4:1"},
  {"ticker":"XPEV","name":"XPENG INC","market":"New York","ratio":"4:1"},
  {"ticker":"XROX","name":"Xerox Holding Corporation","market":"NYSE","ratio":"1:1"},
  {"ticker":"XYZ","name":"Square Inc.","market":"NYSE","ratio":"20:1"},
  {"ticker":"YELP","name":"Yelp Inc.","market":"NYSE","ratio":"2:1"},
  {"ticker":"YZCA","name":"Yanzhou Coal Mining Co. Ltd.","market":"OTC US","ratio":"2:1"},
  {"ticker":"ZM","name":"Zoom Video Communications Inc.","market":"NASDAQ","ratio":"47:1"}
]

// BYMA ticker -> US ticker overrides (BYMA usa tickers diferentes para algunos papeles)
export const TICKER_OVERRIDES: Record<string, string> = {
  'BRKB': 'BRK.B',
  'BA.C': 'BAC',
  'BBV': 'BBVA',
  'BNG': 'BG',
  'PKS': 'PKX',
  'TEN': 'TS',
  'TEFO': 'TEF',
  'TRVV': 'TRV',
  'TXR': 'TX',
  'WBO': 'WB',
  'NOKA': 'NOK',
  'XROX': 'XRX',
  'AOCA': 'ACH',
  'HNPIY': 'HNP',
  'TIIAY': 'TI',
  'SIEGY': 'SIEGY',
  'BAYN': 'BAYRY',
  'ADS': 'ADDYY',
  'BAS': 'BASFY',
  'BSN': 'DANOY',
  'DTEA': 'DTEGY',
  'MBG': 'MBGAF',
  'NEC1': 'NIPNF',
  'EOAN': 'EONGY',
  'PCRF': 'PCRFY',
  'ATAD': 'OAOFY',
  'HHPD': 'HNHPF',
  'LKOD': 'LUKOY',
  'NLM': 'NLMK',
  'OGZD': 'OGZPY',
  'YZCA': 'YZCAY',
  'FMCC': 'FMCC',
  'FNMA': 'FNMA',
}

// Markets where we only compute implied USD (no real US-exchange price)
export const NON_US_MARKETS = ['B3', 'BOVESPA', 'FRANKFURT', 'XETRA', 'LONDON STOCK EXCHANGE', 'OTC', 'OTC US', '-']
